data_paths:
  raw_data_path: "./../artifacts/data/raw_data"
  clean_data_path: "./../artifacts/data/cleaned_data"
  processed_data_path: "./../artifactes/processed_data"
  raw_data_file: loan_approval_dataset.csv
  
mlflow:
  run_name: first_model